In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

### Preparing data

In [2]:
df = pd.read_csv("Dataset/Boston_house_price.csv")
df.head()

Unnamed: 0     CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  \
0           0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0   
1           1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0   
2           2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0   
3           3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0   
4           4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0   

     TAX  PTRATIO       B  LSTAT  price  
0  296.0     15.3  396.90   4.98   24.0  
1  242.0     17.8  396.90   9.14   21.6  
2  242.0     17.8  392.83   4.03   34.7  
3  222.0     18.7  394.63   2.94   33.4  
4  222.0     18.7  396.90   5.33   36.2

In [3]:
df.drop('Unnamed: 0',axis=1,inplace=True)
df.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  price  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [4]:
# Checking information of dataframe 
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    float64
 9   TAX      506 non-null    float64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    506 non-null    float64
 13  price    506 non-null    float64
dtypes: float64(14)
memory usage: 55.5 KB


In [161]:
#Shape of dataframe
df.shape

(506, 14)

In [78]:
# Startistical description of dataframe:
df.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677082   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT       price  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

### Handling Null values:

In [79]:
#Chceking null and missing values:
df.isnull().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
price      0
dtype: int64

### Preparing data for training: 

In [5]:
# Seperating dependent and independent data from dataframe:
X= df.iloc[:,:-1]
X.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900  1.0  296.0   
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671  2.0  242.0   
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671  2.0  242.0   
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622  3.0  222.0   
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622  3.0  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [6]:
y=df['price']
y.head()

0    24.0
1    21.6
2    34.7
3    33.4
4    36.2
Name: price, dtype: float64

In [7]:
# Train test split:
from sklearn.model_selection import train_test_split

In [8]:
# Training our data:
X_train , X_test , y_train , y_test = train_test_split(X,y,test_size =(0.3),random_state=42)

In [9]:
#Scaling:
from sklearn.preprocessing import StandardScaler

In [10]:
scaler = StandardScaler()
scaler

StandardScaler()

### Model training and prediction: 

In [11]:
X_train = scaler.fit_transform(X_train)

In [13]:
X_test = scaler.transform(X_test)
X_test

c:\Users\AKASH\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-0.46684151, -0.52749891, -1.75430529, ..., -8.44094644,
        -4.13918731, -1.8159044 ],
       [-0.467354  , -0.44902113, -1.70514771, ..., -8.24404657,
        -4.1390015 , -1.9251358 ],
       [-0.46663907, -0.52749891, -1.26085482, ..., -7.7517969 ,
        -4.13990268, -1.63689177],
       ...,
       [-0.46053112, -0.52749891, -1.7095219 , ..., -8.28342654,
        -4.14097905, -1.90332917],
       [-0.38723778, -0.52749891, -1.46165105, ..., -7.73210691,
        -4.1783813 , -1.67356656],
       [-0.32424582, -0.52749891, -1.46165105, ..., -7.73210691,
        -4.14011371, -1.66920524]])

In [14]:
# Linear regression classifier:
from sklearn.linear_model import LinearRegression

In [15]:
model = LinearRegression()
model

LinearRegression()

In [16]:
model.fit(X_train,y_train)

LinearRegression()

In [17]:
# Printing coefficient and intercept:
print(model.coef_)
print(model.intercept_)

[-1.10834602  0.80843998  0.34313466  0.81386426 -1.79804295  2.913858
 -0.29893918 -2.94251148  2.09419303 -1.44706731 -2.05232232  1.02375187
 -3.88579002]
23.01581920903955


In [18]:
#Parameters of model:
model.get_params()

{'copy_X': True, 'fit_intercept': True, 'n_jobs': None, 'positive': False}

In [19]:
# Predicting test data values:
reg_pred =model.predict(X_test)
reg_pred

array([ 39.04510117,  60.42575198,  22.02289883,  47.430121  ,
        10.1616309 ,  45.98703853,  29.39817931,  20.34394737,
        33.58450536,  25.63499523,  42.39562987,  32.27903318,
         1.00944614,  45.07566074,  34.5423654 ,  27.44677663,
        25.44436869,   3.20179647,  58.41352445,   9.46303961,
        42.37404921,  46.58419491,  27.48901084,  29.95070711,
         8.25867331,  22.13881748,  43.64434339,  12.27858124,
        48.97369018,  24.08176873,  33.87244894,  39.07743367,
        22.20083392,  -1.9167273 ,  25.13149437, -11.70565654,
        47.14474806,  32.12111249,  49.53779011,  48.2884569 ,
        21.31738594,  45.65860749,  60.36435916,  44.01843254,
        40.9881054 ,   8.8508354 ,  28.03876746,  49.32573671,
        26.66649042,  36.0500866 ,  32.84426687,  50.41647771,
        30.38287896,  38.04835436,  38.20450015,  26.92558411,
         6.43042073,  52.55331249,  44.71563496,  39.81047075,
        43.91161996,  53.89783927,  40.33026117,  27.18

In [20]:
## Residuals
residuals=y_test-reg_pred
residuals

173   -15.445101
274   -28.025752
491    -8.422899
72    -24.630121
452     5.938369
         ...    
441     9.943703
23    -13.858065
225    -2.827429
433     3.283115
447     6.171468
Name: price, Length: 152, dtype: float64

In [21]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error

print(mean_absolute_error(y_test,reg_pred))
print(mean_squared_error(y_test,reg_pred))
print(np.sqrt(mean_squared_error(y_test,reg_pred)))

13.833974322926608
258.5011630049598
16.077971358506638


In [22]:
df[-1:]

CRIM   ZN  INDUS  CHAS    NOX    RM   AGE    DIS  RAD    TAX  PTRATIO  \
505  0.04741  0.0  11.93   0.0  0.573  6.03  80.8  2.505  1.0  273.0     21.0   

         B  LSTAT  price  
505  396.9   7.88   11.9

In [23]:
#predicting values :
arr = np.array([0.04741,0.0,11.93,0.0,0.573,6.03,80.8,2.505,1.0,273.0,21.0,396.9,7.88])
ar =arr.reshape(1,-1)
ar

array([[4.741e-02, 0.000e+00, 1.193e+01, 0.000e+00, 5.730e-01, 6.030e+00,
        8.080e+01, 2.505e+00, 1.000e+00, 2.730e+02, 2.100e+01, 3.969e+02,
        7.880e+00]])

In [24]:
ar= scaler.transform(ar)
ar

c:\Users\AKASH\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


array([[-0.41214416, -0.50512499,  0.11501907, -0.28154625,  0.13496618,
        -0.41168839,  0.4343796 , -0.59390394, -0.97798895, -0.80609114,
         1.20785901,  0.42854113, -0.63938418]])

In [25]:
model.predict(ar)

array([22.61270745])

### Dumping our scaler and model :

In [26]:
import pickle

In [27]:
pickle.dump(model,open('model.pkl','wb'))

In [28]:
pickle.dump(scaler,open('scaler.pkl','wb'))